[package]
name = "grid"
version = "0.1.0"
authors = ["daxpedda <daxpedda@gmail.com>", "Luni-4 <luni-4@hotmail.it>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced =  { git = "https://github.com/hecrj/iced.git", rev = "20177e4" }
iced_aw = { path = "../..", default-features = false, features = ["grid"] }
