[package]
name = "menu"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
iced_aw = { workspace = true, features = [
    "menu",
    "quad",
    "icons"
] }
iced = {workspace = true, features = ["svg"]}