[package]
name    = "cupertino-switch"
version = "0.1.0"
authors = ["Brett Byler <bbyler@protonmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.9.0", features = [] }
iced_aw = { path = "../../../", features = ["cupertino"] }

